function [markers] = get_markers(c3d)

pyCGM24 = { ...
    'LFHD', 'RFHD', 'LBHD', 'RBHD', ...
    'C7', 'T10', 'CLAV', 'STRN', 'RBAK', ...
    'LSHO', 'LELB', 'LWRA', 'LWRB', 'LFIN', 'LUPA', 'LFRM', ...
    'RSHO', 'RELB', 'RWRA', 'RWRB', 'RFIN', 'RUPA', 'RFRM', ...
    'LASI', 'RASI', 'LPSI', 'RPSI', ...
    'LTHI', 'LKNE', 'LTIB', 'LANK', 'LTHIAP', 'LTIBAP', ...
    'RTHI', 'RKNE', 'RTIB', 'RANK', 'RTHIAP', 'RTIBAP', ...
    'LHEE', 'LTOE', 'LVMH', 'LFMH', ...
    'RHEE', 'RTOE', 'RVMH', 'RFMH', ...
};

markers=struct();
labels=c3d.parameters.POINT.LABELS.DATA;
for i=1:length(labels)
    if ismember(labels{i},pyCGM24)
        markers.(labels{i})=squeeze(c3d.data.points(:,i,:))';
    end
end

end